import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createProxy} from '../server.mjs';
const token='a-device-token-longer-than-24-characters';
async function setup(t,fetchImpl){const s=createProxy({apiKey:'server-secret',modelId:'ppe-test/1',supportedPpe:['helmet','vest'],tokens:[token],fetchImpl});await new Promise(r=>s.listen(0,'127.0.0.1',r));t.after(()=>{s.closeAllConnections();s.close();});return `http://127.0.0.1:${s.address().port}/infer`;}
test('rejects unauthenticated requests without invoking provider',async t=>{const url=await setup(t,()=>{throw Error('must not call');});assert.equal((await fetch(url,{method:'POST'})).status,401);});
test('validates JPEG and confidence',async t=>{const url=await setup(t,()=>{throw Error('must not call');});const r=await fetch(url,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({image:'aGVsbG8='})});assert.equal(r.status,400);});
test('normalizes inference response and keeps API key server side',async t=>{const url=await setup(t,async (provider,options)=>{assert.equal(provider.hostname,'detect.roboflow.com');assert.equal(provider.searchParams.get('confidence'),'60');assert.equal(options.body,'/9j/2Q==');return {ok:true,json:async()=>({predictions:[],image:{width:640,height:480},secret:'never-forward'})};});const r=await fetch(url,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({image:'/9j/2Q==',confidence:.6})});assert.equal(r.status,200);assert.deepEqual(await r.json(),{predictions:[],image:{width:640,height:480},supported_ppe:['helmet','vest']});});
test('provider errors are redacted',async t=>{const url=await setup(t,async()=>{throw Error('server-secret');});const r=await fetch(url,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({image:'/9j/2Q=='})});assert.equal(r.status,502);assert.ok(!(await r.text()).includes('server-secret'));});
